import Link from "next/link";
import { prisma } from "@/lib/prisma";
import { BuildCard } from "@/components/BuildCard";
export default async function Home(){
 let builds:any[]=[]; let posts:any[]=[];
 if(process.env.DATABASE_URL){ builds=await prisma.build.findMany({include:{parts:true,tasks:true},orderBy:{updatedAt:"desc"},take:6}); posts=await prisma.journalPost.findMany({include:{author:true,build:true},orderBy:{createdAt:"desc"},take:4}); }
 return <main><div className="container"><section className="hero"><div className="eyebrow">Automotive build community</div><h1>Build it. Track it. Share it.</h1><p>BuildTrack gives car people one place to document builds, organize parts and tasks, follow projects, and get help when the wrenching gets weird.</p><div className="actions"><Link className="btn primary" href="/garage">Open my garage</Link><Link className="btn" href="/builds">Explore builds</Link></div></section>
 <section className="section"><div className="sectionhead"><h2>Featured builds</h2><Link className="muted small" href="/builds">View all →</Link></div><div className="grid">{builds.length?builds.map(b=><BuildCard key={b.id} build={b}/>):<div className="card"><h3>Your garage starts here.</h3><p className="muted">Run the database seed to load the demo Evo build, then replace it with your own vehicles.</p><Link className="btn primary" href="/garage">Go to garage</Link></div>}</div></section>
 <section className="section grid2"><div><div className="sectionhead"><h2>Latest updates</h2><Link className="muted small" href="/community">Community →</Link></div><div className="list">{posts.length?posts.map(p=><article className="listitem" key={p.id}><strong>{p.title}</strong><p className="muted small">{p.body}</p><span className="muted small">{p.author.name} · {p.build?.title ?? "Community"}</span></article>):<div className="card muted">Community updates will appear here.</div>}</div></div><aside className="card"><h3>Built for real projects</h3><p className="muted">Track parts, maintenance, expenses, progress photos, questions and answers without losing the story of the car.</p><Link className="btn" href="/help">Ask for help</Link></aside></section></div></main>
}
